modLoader="javafml"
loaderVersion="[36,)"
license="All rights reserved"
[[mods]]
modId="beta_brewing_system"
version="${file.jarVersion}"
displayName="远古酿造系统"
authors="edebe"
[[dependencies.beta_brewing_system]]
    modId="forge"
    mandatory=true
    versionRange="[36,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.beta_brewing_system]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,1.17)"
    ordering="NONE"
    side="BOTH"
