modLoader="javafml"
loaderVersion="[36,)"
license="All rights reserved"
[[mods]]
modId="betabrewingsystem"
version="${file.jarVersion}"
displayName="Beta Brewing System"
authors="edebe"
[[dependencies.betabrewingsystem]]
    modId="forge"
    mandatory=true
    versionRange="[36,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.betabrewingsystem]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2,1.20)"
    ordering="NONE"
    side="BOTH"